server:
  port: ${PORT:8080}
spring:
  application:
    name: ${name}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
